import 'package:flutter/material.dart';

Color transparent = Colors.transparent;
Color white = Colors.white;
Color black = Colors.black;
Color clubsBackground = Color(0xffF5F7FF);
Color clubsBackground2 = Color(0xffdde4ff);
Color loginSignup = Color(0xffF1F6FF);
Color passwordColor = Color(0xffDDE8FC);
Color fontColor = Color(0xff131a31);
Color fontColorLight = Color(0x80131a31);
Color red = Color(0xffFF5E5E);
Color sizzlingRed = Color(0xffE63946);
Color blue = Color(0xff60A2FF);
Color blueSplash = Color(0xff4389EC);
Color neonBlue = Color(0xff5863F8);
Color slateBlue = Color(0xff7F7EFF);
Color violet = Color(0xff8948FC);
Color blueViolet = Color(0xff8338EC);
Color violetSplash = Color(0xff6C29E4);
Color faintViolet = Color(0xffF6F0FF);
Color darkBlue = Color(0xff6281B6);
Color yellow = Color(0xffFFC43D);
Color mango = Color(0xffFFBD00);
Color orange = Colors.orange;
Color aqua = Color(0xff8AFFC1);
Color aquaDark = Color(0xff5dfdcb);
Color teal = Colors.teal;
